#!/bin/bash

# See the docs for automated docker builds: https://docs.docker.com/docker-cloud/builds/advanced/

# $IMAGE_NAME var is injected into the build so the tag is correct.

echo "Build hook running"
export DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
docker build --build-arg BUILD_DATE=$DATE \
             --build-arg VCS_REF=$COMMIT \
             --build-arg BRANCH=$BRANCH \
             -t ${IMAGE_NAME} .
